apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: application
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  {{- if eq .Values.librenmsServices.mysql.external.enabled false }}
  mysql_root_password: {{ required "MySQL root password must be provided (credentials.mysql.rootPassword)" .Values.credentials.mysql.rootPassword | b64enc }}
  {{- end }}
  librenms_mysql_user: {{ required "MySQL user must be provided (credentials.mysql.user)" .Values.credentials.mysql.user | b64enc }}
  librenms_mysql_password: {{ required "MySQL password must be provided (credentials.mysql.password)" .Values.credentials.mysql.password | b64enc }}
  {{- if eq .Values.Application.authMechanism "mysql" }}
  librenms_administrative_user: {{ required "administrative user must be provided (credentials.application.administrativeUser)" .Values.credentials.application.administrativeUser | b64enc }}
  librenms_administrative_password: {{ required "administrative password must be provided (credentials.application.administrativePassword)" .Values.credentials.application.administrativePassword | b64enc }}
  librenms_administrative_email: {{ required "administrative email must be provided (credentials.application.administrativeEmail)" .Values.credentials.application.administrativeEmail | b64enc }}
  {{- end }}
  {{- if eq .Values.Application.authMechanism "ldap" }}
  {{- if .Values.credentials.ldap.userDN }}
  librenms_ldap_user: {{ .Values.credentials.ldap.user | b64enc }}
  librenms_ldap_userdn: {{ .Values.credentials.ldap.userDN | b64enc }}
  {{- else }}
  librenms_ldap_user: {{ required "LDAP bind user must be provided (credentials.ldap.user)" .Values.credentials.ldap.user | b64enc }}
  {{- end }}
  librenms_ldap_password: {{ required "LDAP bind password must be provided (credentials.ldap.password)" .Values.credentials.ldap.password | b64enc }}
  {{- end }}
  {{- if eq .Values.Application.authMechanism "active_directory" }}
  {{- if .Values.credentials.active_directory.userDN }}
  librenms_ad_user: {{ .Values.credentials.active_directory.user | b64enc }}
  librenms_ad_userdn: {{ .Values.credentials.active_directory.userDN | b64enc }}
  {{- else }}
  librenms_ad_user: {{ required "Active Directory bind user must be provided (credentials.active_directory.user)" .Values.credentials.active_directory.user | b64enc }}
  {{- end }}
  librenms_ad_password: {{ required "Active Directory bind password must be provided (credentials.active_directory.password)" .Values.credentials.active_directory.password | b64enc }}
  {{- end }}
  librenms_redis_password: {{ required "Redis password must be provided (credentials.redis.password)" .Values.credentials.redis.password | b64enc }}
  librenms_application_key: {{ required "application key must be provided (credentials.application.key)" .Values.credentials.application.key | b64enc }}
