	// git repository info
	def gitRepository = 'http://172.10.0.5/root/charts.git'
	def gitBranch = 'main'

	// Image infor in registry
	def imageGroup = 'staging'
	def appName = "librenms-dist-poller"
	def namespace = "public"

	//helm param for upgrades
	def helmRelease="librenms"
	def helmValues = "/var/lib/jenkins/workspace/$helmRelease/$appName/values.yaml"
	def helmChart = "/var/lib/jenkins/workspace/$helmRelease/$appName"
	def k8sEnv = "/var/lib/jenkins/workspace/$helmRelease/$appName/k8s"

	// harbor-registry credentials
	def registryCredential = 'jenkin_harbor'
	// gitlab credentials
	def gitlabCredential = 'jenkin_gitlab'
	
	dockerBuildCommand = './'
    // def version = "prod-0.${BUILD_NUMBER}"
    def version = "latest"

	pipeline {
		agent any
		
		environment {
			DOCKER_REGISTRY = 'https://repo.cpt.gov.vn'
			DOCKER_IMAGE_NAME = "${imageGroup}/${appName}"
			DOCKER_IMAGE = "repo.cpt.gov.vn/${DOCKER_IMAGE_NAME}"
			DOCKER_FILE = "$helmChart/Dockerfile"
		}

		stages {
		
			stage('Checkout project') 
			{
			  steps 
			  {
				echo "checkout project"
				git branch: gitBranch,
				   credentialsId: gitlabCredential,
				   url: gitRepository
				sh "git reset --hard"				
			  }
			}

			stage('Build and push image') 
			{
			  steps 
			  {
				script {

			// 			// Build
						sh "docker build -t ${DOCKER_IMAGE}:${version} -f ${DOCKER_FILE} $helmChart"
						//Authenticating with the Docker registry
						withCredentials([usernamePassword(credentialsId: gitlabCredential, url: gitRepository, passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin ${DOCKER_REGISTRY}"
                    }
                    // Pushing the Docker image to the registry
                  		sh "docker push ${DOCKER_IMAGE}:${version}"
                }
						// app = docker.build(DOCKER_IMAGE_NAME, dockerBuildCommand)
						// docker.withRegistry( DOCKER_REGISTRY, registryCredential ) {                       
						//    app.push(version)
						// }
				    
			// // 			sh "docker rmi ${DOCKER_IMAGE_NAME} -f"
			// 			sh "docker push ${DOCKER_IMAGE}:${version}"		
			// 		//	sh "docker rmi ${DOCKER_IMAGE}:latest -f"				
					
			  }
			}
			stage('Precheck Kubernetes Cluster') {
				steps {
					script {
						try {
							def namespaceExists = sh(
								script: "kubectl --kubeconfig=$k8sEnv get namespace $namespace",
								returnStatus: true
							)
							if (namespaceExists != 0) {
								echo "Namespace $namespace does not exist. Creating..."
								sh "kubectl --kubeconfig=$k8sEnv create namespace $namespace"
							} else {
								echo "Namespace $namespace already exists."
							}
						} catch (Exception e) {
							echo "Stage failed but ignoring the failure."
						}
					}
				}
			}
			stage('Deploy to Kubernetes Cluster') {
				steps {
					script {
						echo "Deploy to k8s"
						// sh "helm --namespace=$namespace --kubeconfig=$k8sEnv delete $appName || true"
						sh "helm --namespace=$namespace --kubeconfig=$k8sEnv upgrade --install $helmRelease -f $helmValues $helmChart  --set=image.tag=$version"
				}
			}
		}
	}
	}
	