apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-app
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-app
    spec:
      containers:
      - name: {{ template "fullname" . }}-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.phpService.port }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.phpService.port }}
          initialDelaySeconds: 10
          timeoutSeconds: 5
