apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "librenms.fullname" . }}-rrdcached
  labels:
    {{- include "librenms.rrdcached.labels" . | nindent 4 }}
data:
  TZ: {{ .Values.timezone | default "Etc/UTC" }}
  LOG_LEVEL: "LOG_INFO"
  WRITE_TIMEOUT: "1800"
  WRITE_JITTER: "900"
  WRITE_THREADS: "4"
  FLUSH_DEAD_DATA_INTERVAL: "3600"
