apiVersion: v2
name: librenms-beta1
type: application
description: SNMP monitoring for network devices
keywords:
  - nms
  - network
  - snmp
  - monitoring
home: https://cpt.gov.vn
icon: https://i.ibb.co/whw7Bhw/Libre-NMS-Logo.png
sources:
  - https://github.com/librenms/docker
maintainers:
  - name: hath
    url: https://cpt.gov.vn

version: 1.0.17
appVersion: "latest"

dependencies:
  - name: mariadb
    alias: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.6.3
    condition: mysql.install
  - name: memcached
    repository: https://charts.bitnami.com/bitnami
    version: 5.15.7
    condition: memcached.install
    tags:
      - distributed-poller
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.1
    condition: redis.install
    tags:
      - distributed-poller
