apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Release.Namespace }}
  name: test-console
  labels:
    application: librenms
    component: test-console
spec:
  containers:
  - name: console
    image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    imagePullPolicy: Always
    env:
    - name: LIBRENMS_MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_mysql_user
    - name: LIBRENMS_MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_mysql_password
    - name: LIBRENMS_REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: application
          key: librenms_redis_password
