apiVersion: v1
description: A Helm chart for Kubernetes
name: cpt-librenms
version: 0.1.42
home: https://cpt.gov.vn
icon: https://i.ibb.co/whw7Bhw/Libre-NMS-Logo.png
sources:
  - https://github.com/librenms/docker
maintainers:
  - name: hath
    url: https://cpt.gov.vn