# Default values for php-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your template
replicaCount: 1
image:
  repository: repo.cpt.gov.vn/staging/librenms-standalone
  tag: "latest"
  pullPolicy: Always

phpService:
  name: web
  type: ClusterIP
  port: 80

nodeSelector: 
  cloud: openstack

ingress:
  enabled: true
  # Used to  createe Ingress record (should used with service.type: ClusterIP).
  hosts:
    - librenms1.cpt.gov.vn
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespaces
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi


persistence:
  enabled: true
  size: 10Gi
  existingClaim: ""
  mountPath: /opt/
  storageClass: ""
  annotations: {}
  accessModes:
      #- ReadWriteMany
    - ReadWriteOnce
