# Default values for phpfpm-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: repo.cpt.gov.vn/staging/libre-php
  tag: latest
  pullPolicy: IfNotPresent
nginxService:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
phpfpmService:
  name: phpfpm
  type: ClusterIP
  phpfpmPort: 9000
ingress:
  enabled: true
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - libre.cpt.gov.vn
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
config:
  nginx.conf: |-
    server {
      listen      80;
      server_name librenms.example.com;
      root        /opt/librenms/html;
      index       index.php;

      charset utf-8;
      gzip on;
      gzip_types text/css application/javascript text/javascript application/x-javascript image/svg+xml text/plain text/xsd text/xsl text/xml image/x-icon;
      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }
      location ~ [^/]\.php(/|$) {
        fastcgi_pass unix:/run/php-fpm-librenms.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi.conf;
      }
      location ~ /\.(?!well-known).* {
        deny all;
      }
      }


resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi
