{{ range .Values.Devices }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ .DeviceName }}
spec:
  clusterIP: None
  selector:
    component: {{ .DeviceName }}
  ports:
  - port: 161
    targetPort: 161
    protocol: UDP
    name: snmp-udp
  - port: 161
    targetPort: 161
    protocol: TCP
    name: snmp-tcp
---
apiVersion: v1
kind: Pod
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ .DeviceName }}
  labels:
    application: librenms
    component: {{ .DeviceName }}
spec:
  containers:
  - name: device
    image: {{ $.Values.image.repositoryRoot }}-{{ .SNMPVersion }}:{{ $.Values.image.tag }}
    imagePullPolicy: Always
---
{{ end }}
