{{- if .Values.vault.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccount.name }}
  labels:
    app: {{ include "fullname" . }}-poller
{{- end }}


