apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
data:
  vault-agent-config.hcl: |-
    {{`{{ with secret "secret/public-secret/librenms" }}
    {{ range $k, $v := .Data.data }}
    export {{ $k }}={{ $v }}
    {{ end }}
    {{ end }}`}}