apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullname" . }}-config
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  config.php: |
    <?php
    $config['db_host'] = '{{ include "fullname" . }}-mariadb:42217';
    $config['db_port'] = '3306';
    $config['db_user'] = 'admin';
    $config['db_pass'] = 'cpt@123';
    $config['db_name'] = 'librenms';
    $config['db_socket'] = '';
    $config["own_hostname"] = '{{ include "fullname" . }}';
    $config["base_url"] = '/';
    $config["rrdcached"] = '{{ include "fullname" . }}-rrdcached:42217';
    $config["distributed_poller"] = {{ gt (.Values.poller.replicaCount | int) 0 | ternary "true" "false" }};
    $config["distributed_poller_name"] = php_uname('n');
    $config["distributed_poller_group"] = '0';
    $config["distributed_poller_memcached_host"] = '{{ include "fullname" . }}-memcached';
    $config["distributed_poller_memcached_port"] = 11211;

