{{- $fullName := include "fullname" . }}
{{- $secretName := printf "%s-env" $fullName }}
{{- $oldSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  DB_PASSWORD: {{ .Values.mysql.auth.password | default "password" | b64enc }}
{{- if and .Values.redis.install .Values.redis.auth.enabled }}
  REDIS_PASSWORD: {{ required "Missing .Values.redis.auth.password" .Values.redis.auth.password | b64enc }}
{{- end }}
{{- if $oldSecret }}
{{- with $oldSecret.data }}
  APP_KEY: {{ .APP_KEY }}
{{- end }}
{{- else if .Values.app.key }}
  APP_KEY: {{ .Values.app.key | b64enc }}
{{- else }}
  APP_KEY: {{ printf "base64:%s" (randAscii 32 | b64enc) | b64enc }}
{{- end }}
