apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-secret
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  DB_PASSWORD: {{ b64enc (vault "secret/public-secret/librenms" "data.db") }}
  REDIS_PASSWORD: {{ b64enc (vault "secret/public-secret/librenms" "data.redis") }}
  APP_KEY: {{ b64enc (vault "secret/public-secret/librenms" "data.appkey") }}
